spring.application.name=thanhcongvn

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.format_sql=false

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=1024

home.featured-categories=coi-hu-bao-dong,tu-dieu-khien,coi-quay-tay,may-thoi-khi-va-dem-hoi-cuu-ho,phu-kien-an-ninh

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.profiles.active=local